name: R Package Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.x

      - name: Install Dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run Tests
        run: |
          library(simgehugo732A94lab3)  # Replace with your actual package name
          testthat::test_dir("tests")
        shell: Rscript {0}
